### ISSUE TITLE
1.x release?

### ISSUE THREAD

**Issue by calebmer** [contain-rs/linear-map#11]
When will the `1.x` release for this module be? If the API is stable and won't change why can't it be `1.x` now?

**Comment by apasel422** [comment]
I'm working on a PR that will clean some things up and bump the version.

**Comment by calebmer** [comment]
Could that version bump be to `1.0.0`?

**Comment by apasel422** [comment]
Sure. The only blocker right now is #13.

**Comment by calebmer** [comment]
Thanks!
